### PR TITLE
fix overlapped issue of create Iteration modal and workItem detail.

### PR DESCRIPTION
**Pull request by vikram-raj**
- Reduce the z-index of detail panel.
Fix: #810

### CODE REVIEW

**Comment by debloper** [comment]
Seems like a fix for now, but we'll hit a point where unknown order/precedence of z-index of multiple elements will cause regressions.

I suggest having a z-index order/precedence range guide of our UI, and get it reviewed by @fabric8io/uxd. Knowing that a modal can have 1000-1200 z-index, a floating button or something can have 500-600 z-index and a sliding sidebar can have 100-200 z-index etc (all these are for e.g. only, please don't nitpick on values) will make a huge difference on how many complicated regressions we will avoid in later stages of the app.

**Comment by vikram-raj** [comment]
@debloper yes, I agree with you. Need a feedback from @fabric8io/uxd.

**Comment by nimishamukherjee** [comment]
@vikram-raj please create an issue on https://github.com/fabric8io/fabric8-ux for this (which element would sit on top of which)?

**Comment by mindreeper2420** [comment]
Questions:
- why does the panel have a z-index of 100? Why so high? Also, I was unable to find a z-index for any other element - modal, navigation, or anything else.
- Do other elements already have z-indexes?
- Is Bootstrap / PatternFly being used to control the layering, as it should? Those frameworks cover layering for modals, slideouts, and other aspects. Custom code should not be there for that. @michaelkleinhenz, @michaelvirgil - how much of Bootstrap/PatternFly is being used at this point?

We will most likely not be able to give you a z-index for every single element - that is what the embedded frameworks are for. The CSS for each framework will properly handle the button layering, modal layering, etc.

**Comment by vikram-raj** [comment]
- z-index property only affects elements that have position value other than static. And modal have z-index 1050. which is set by bootstrap and to make sure it will be always on top.

- Not all elements have z-index property. Z-index property set to only those elements which have position fixed or absolute property.

- Bootstrap / Patternfly control the layering by giving z-index property.

@mindreeper2420  Here we just wanted to know the order of layering of elements. (modal, detail page, kabal menu.)

**Comment by mindreeper2420** [comment]
@vikram-raj - As you stated, Bootstrap / PatternFly control the layering by giving the z-index property. For anything not covered by either of those libraries, please use what makes logical sense - i.e. the kabob should not appear above the detail panel.

**Comment by vikram-raj** [comment]
Ok @mindreeper2420. Thanks.

**Comment by nimishamukherjee** [comment]
[test]

**Pull request merged**
