### PR TITLE
Story 1172: Dynamic Forms

### PR DESCRIPTION
**Pull request by michaelkleinhenz**

### CODE REVIEW

**Comment by sanbornsen** [comment]
[test]

**Comment by nimishamukherjee** [comment]
Functional test fails for description: `Failed: No element found using locator: By(css selector, *[id="wi-detail-desc"])`

**Comment by michaelkleinhenz** [comment]
[test]

**Comment by michaelkleinhenz** [comment]
@nimishamukherjee yes, @ldimaggi said that this is a problem in the tests.

**Comment by naina-verma** [comment]
@nimishamukherjee , #1412  this the issue , if you can paste the Test Case name i can confirm right away !

**Pull request merged**
