### PR TITLE
fix(create new work item): Add a few keyboard short cuts for navigation and selection.

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Use keyboard keys to navigate and select a work item. 
- Left or down to go to the previous work item type
- Top or right to go to the next work item type
- Enter to select a work item type
- Select a work item type using the starting letter of the work item type

To fix - if there are two or more work items with the same starting letter, the same work item, in descending alphabetical order, would get selected each time the letter is pressed.

### CODE REVIEW

**Comment by nimishamukherjee** [comment]
@mindreeper2420 , @michaelkleinhenz please have a look at this PR.

This adds keyboard short cuts for selecting a work item type. To denote the selected work item, I have used the class "card-pf-accented"

selectwit

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1633-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1633-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1633-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1633-fabric8-planner.int.rdu2c.fabric8.io

**Comment by catrobson** [comment]
There is a document that captures all the keyboard shortcuts that we should have so that we don't run into keyboard shortcut overwrites across the platform here:  https://docs.google.com/spreadsheets/d/1KglEj4LHhSXO55ksfUgl3jZv6WihibTGFUQixwOMM5w/edit#gid=0

**Comment by mindreeper2420** [comment]
@nimishamukherjee this is the proper class for a selected Card: `.card-pf-view.card-pf-view-select.active` and will apply this style: `border: 2px solid $color-pf-blue-300;`

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1633-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
Closing for now as this is not a summit priority. Also requires some amount of work to implement keyboard shortcuts laid out by UX.

**Pull request closed without merging**
