### PR TITLE
Fix for Area/Iteration selection

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
Removed the empty value from the Area dropdown. Fixed paths for areas in dropdown. Added an option for specifying a non-selectable null label to the typeahead dropdown. The latter is cool :-) and needed for the current bug in the core that allows the Area to be set to empty (instead of rejecting that update). There will be another PR for core fixing that later today.
Fixed the iteration dropdown as well with proper root iteration name.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1703-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1703-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1703-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1703-fabric8-planner.int.rdu2c.fabric8.io

**Comment by michaelkleinhenz** [comment]
As per @maxandersen 's idea, the entries are now sorted by length, putting the shortest on top.

**Pull request merged**
