### PR TITLE
fix(test): fixed WI title alert scenarios

### PR DESCRIPTION
**Pull request by rgarg1**
Empty Wi title scenarios were failing as class name and error message changed; fixed!

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1975-fabric8-planner.int.rdu2c.fabric8.io

**Comment by rgarg1** [comment]
No failures for me. Pls check if you are running with my PR https://github.com/fabric8io/fabric8-planner/pull/1961 changes.

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1975-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1975-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
