### PR TITLE
fix(test): path to spec files fixed

### PR DESCRIPTION
**Pull request by rgarg1**
Path of EXCLUDED spec files fixed to ensure they are NOT run in regular runs. They were running post runtime refactoring and causing 5 additional failures.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1961-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1961-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1961-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1961-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1961-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
[test]

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1961-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1961-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
