### PR TITLE
Refactoring: New Runtime

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
This creates a new external runtime that contains a seperate, isolated and minimal dev environment for running the Planner on a local machine for development and testing. It is also used as the basis for the functional tests. Unit tests are now run detached from the runtime.

### CODE REVIEW

**Comment by michaelkleinhenz** [comment]
To run the runtime, follow the instructions in runtime/README.md.

**Comment by nimishamukherjee** [comment]
[test]

**Comment by nimishamukherjee** [comment]
[test]

**Comment by nimishamukherjee** [comment]
[test]

**Pull request merged**
