### PR TITLE
Adding funtional tests for Area's

### PR DESCRIPTION
**Pull request by naina-verma**
Adding funtional tests for Area's

### CODE REVIEW

**Comment by naina-verma** [comment]
@nimishamukherjee , can you please review this PR
Second commit is for fixing the protractor.config.js, because if you pull current master functional tests will fail due to bad configuration!

**Comment by nimishamukherjee** [comment]
[test]

**Comment by naina-verma** [comment]
[test]

**Comment by naina-verma** [comment]
Started
..........................................................................................


90 specs, 0 failures
Finished in 591.736 seconds

[14:41:07] I/launcher - 0 instance(s) of WebDriver still running
[14:41:07] I/launcher - chrome #01 passed
4444/tcp:            10378
8088/tcp:            10408
Functional tests OK

**Pull request merged**
