### PR TITLE
fix(work-item-link): resolve merge conflicts in wi link

### PR DESCRIPTION
**Pull request by SMahil**
resolve merge conflicts in wi link component

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2010-fabric8-planner.int.rdu2c.fabric8.io

**Comment by vikram-raj** [comment]
screenshot from 2017-06-20 11-58-37 - 1

Board view also has the pagination issue. and board view is not covering the full height.

**Comment by vikram-raj** [comment]
Detail add is also not showing the WI type modal.

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2010-fabric8-planner.int.rdu2c.fabric8.io

**Comment by mindreeper2420** [comment]
@vikram-raj @nimishamukherjee @SMahil if testing this in integrated, please do so using PR https://github.com/fabric8io/fabric8-ui/pull/1419. That PR will be merged as soon as Planner builds without error.

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2010-fabric8-planner.int.rdu2c.fabric8.io

**Comment by mindreeper2420** [comment]
@vikram-raj @nimishamukherjee @SMahil @michaelkleinhenz additionally, these issues are going to occur until the Platform PR is merged and the system is rebuilt. Part of this work is to fix outstanding issues after everything has been updated with the removed flexbox layout.

**Comment by SMahil** [comment]
@mindreeper2420 agree. but for today's point of time, we just need to make it presentable for now and then do the whole layout fix what you have mentioned

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2010-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2010-fabric8-planner.int.rdu2c.fabric8.io

**Comment by SMahil** [comment]
@nimishamukherjee @vikram-raj when I pulled this branch into new , I didn't seen any issue regarding detail type page. Can we go ahead with this as the issue does not exist at local?

**Comment by mindreeper2420** [comment]
this issue is blocking PR https://github.com/fabric8io/fabric8-ui/pull/1419

**Comment by nimishamukherjee** [comment]
@SMahil the I'm not able to open the detail add in the snapshot.
Merging this PR as Platform needs it.

**Pull request merged**
