### PR TITLE
fix(fonts): Update font sizes

### PR DESCRIPTION
**Pull request by mindreeper2420**
this PR updates the base font size to 14 pixels. as part of this fix, the Detail Panel was updated to fit the standard form template, in order to properly accommodate the new font size. resetting the base font going forward is handled by the file `_overrides-for-patternfly.scss` using `$font-size-base:`.

### CODE REVIEW

**Comment by nimishamukherjee** [comment]
[test]

**Comment by nimishamukherjee** [comment]
Area drop down is broken
Area dropdown
areadropdown
How it looks now
areanow

**Comment by mindreeper2420** [comment]
@SMahil odd - can you do the refresh browser cache dance again? I'm unable to reproduce those breaks.

**Comment by SMahil** [comment]
@mindreeper2420 Its still same for me.

I have another question. Why don't we have full border-bottom after assignee and before area/iteration wrapper

**Comment by mindreeper2420** [comment]
@SMahil there is a bar below assignee/creator and before area/iteration

**Comment by mindreeper2420** [comment]
@nimishamukherjee area dropdown restored with the latest push. the jumping when you activate the dropdown existed before the font change.

**Comment by SMahil** [comment]
@mindreeper2420 its there but we have padding on left and right side. why not full width?

**Comment by mindreeper2420** [comment]
@SMahil divider lines should actually be removed, per Detail Panel roll-up view: https://redhat.invisionapp.com/share/D4ARY0Z6Z#/222615241_A-0100. PR updated accordingly.

**Comment by mindreeper2420** [comment]
@nimishamukherjee here is an updated screenshot after fixing the Areas dropdown error:
screen shot 2017-03-13 at 6 36 20 pm

**Comment by joshuawilson** [comment]
Why is everyone still testing this in Planner standalone?

**Comment by mindreeper2420** [comment]
@joshuawilson tested inside of Platform - need to file a PR to fabric8-ui to complete the upgrade of the font size. Should I file that and wait until that is merged before completing this?

**Comment by joshuawilson** [comment]
My point is that all of the above images appear to be of the standalone Planner.

**Comment by mindreeper2420** [comment]
pertinent updates to fabric8-ui are made in this PR: https://github.com/fabric8io/fabric8-ui/pull/288, in order for Planner to view properly in an integrated environment.

**Comment by michaelkleinhenz** [comment]
[test]

**Comment by michaelkleinhenz** [comment]
[test]

**Comment by nimishamukherjee** [comment]
@mindreeper2420 the details panel has no padding around the content
nospace

**Comment by nimishamukherjee** [comment]
@mindreeper2420 area drop down has moved to the next line.
areaddnextline

**Comment by mindreeper2420** [comment]
@nimishamukherjee I don't have any of those problems that you noted locally. Cleared browser cache and used different browsers. Are you running standalone or integrated?

**Comment by nimishamukherjee** [comment]
@mindreeper2420 above screeshots are from integrated.

**Comment by nimishamukherjee** [comment]
When I run planner as standalone I get the below errors:
planneronlyerror

**Comment by nimishamukherjee** [comment]
@mindreeper2420 can you confirm if this is the expected font size:
I inspected Create text:
uitext

In the console I got:
inspectfontvalue
 
The font-size:1.2rem;
Is this expected?

**Comment by mindreeper2420** [comment]
@nimishamukherjee my version does not have the `font-size: 1.2em;`. It just has `width: 100%;`

**Comment by mindreeper2420** [comment]
@michaelkleinhenz looks like the failure was on a merge conflict. Do you want me to rebase and update, or do you handle that on the merge?

**Comment by joshuawilson** [comment]
@mindreeper2420 you should rebase in case there are any conflicts. And only an admin can merge something out of date. So it is better if you can fix it.

**Comment by nimishamukherjee** [comment]
1. @mindreeper2420 the UI works fine for me now. I had to run npm run reinstall on fabric8-planner.

2. Can you confirm the expected font-sizes for all the labels on detail's page like Created, Assignees, Creator, Area, and Iteration?

3. The font sizes vary for Total Links and Comments
4. Total links has a scrollbar

fontsizes


Screenshot taken on Fedora 25 + Chrome

**Comment by mindreeper2420** [comment]
@nimishamukherjee expected font styles are correct. The toolbar and different text sizes for the Links and Comments is new though. I will fix.

**Comment by mindreeper2420** [comment]
@nimishamukherjee it turns out that Links and Comments are coded completely different - one uses the PatternFly navigation tabs and the other does not. Do you want that refactored as part of this, or a separate PR (I vote for separate PR-keeps this to just fonts :-) ). @michaelkleinhenz

**Comment by nimishamukherjee** [comment]
@mindreeper2420 ok. Separate PR would do.

**Comment by michaelkleinhenz** [comment]
@mindreeper2420 please rebase.

**Comment by mindreeper2420** [comment]
@michaelkleinhenz rebased

**Comment by joshuawilson** [comment]
@mindreeper2420 it looks like your didn't rebase because there are still conflicts.

**Comment by mindreeper2420** [comment]
@joshuawilson finally fixed...maybe? :)

**Comment by mindreeper2420** [comment]
@michaelkleinhenz just an FYI that the Platform piece of this has been merged. Once this is merged in, everything will display according to the new base font.

**Comment by joshuawilson** [comment]
[test]

**Pull request merged**
