### PR TITLE
Debs pr with all comment update

### PR DESCRIPTION
**Pull request by sanbornsen**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1821-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1821-fabric8-planner.int.rdu2c.fabric8.io

**Comment by sanbornsen** [comment]
This PR is not needed for summit and raised to post_summit branch - https://github.com/fabric8io/fabric8-planner/pull/1822

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1821-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1821-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1821-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
