### PR TITLE
fix(workitemlist): disabled checkboxes.

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
Removed the checkboxes on the work item list. We do now allow multiple selections yet anyway.

### CODE REVIEW

**Comment by maxandersen** [comment]
now -> not, right ? :)

**Comment by mindreeper2420** [comment]
If you remove the check boxes, then what happens to the 'Move' button in the toolbar?

**Comment by michaelkleinhenz** [comment]
I'd say lets keep the move dropdown and change the behaviour that it touches the currently selected entry. After all, we still "select" an entry when clicking on it. @mindreeper2420 ok with that?

**Comment by nimishamukherjee** [comment]
For the touch/select we have the drag behaviour for re-ordering.

**Comment by mindreeper2420** [comment]
@michaelkleinhenz that was not the intention of the original design, as opening a work item was not selecting it for movement. Please reach out to @catrobson for clarification, as she completed the latest designs for the toolbar.

**Comment by catrobson** [comment]
Design intent:
Checkboxes select the row, but do not open the work item.  
Checkboxes only show on hover, but once check remain on screen so you can see all the items you have checked.
Example:  https://redhat.invisionapp.com/share/YVA4PGYA3#/225834565_Multi-Select

I think there are two implementation options:
1. Remove the checkboxes and the move menu completely from the system if we cannot support multi-select in a timely manner
2. Keep the checkboxes and keep the move menu as designed

**Comment by michaelkleinhenz** [comment]
I changed the PR to option #1. I think this makes the most sense.

**Pull request merged**
