### PR TITLE
fix(iterations): fixes the date shifting when used in GMT-X timezones

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
Fixes the one day shift of start and end dates of iterations when used in GMT-X timezones (everything west of Europe).

### CODE REVIEW

**Comment by michaelkleinhenz** [comment]
Fixes https://github.com/fabric8io/fabric8-ui/issues/1188

**Comment by maxandersen** [comment]
why is this even messing with tz values ? shouldn't we always store/manipulate UTC and just render based on current timezone ?

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1824-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1824-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1824-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1824-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
