### PR TITLE
fix(side panel): Wrap long iteration titles.

### PR DESCRIPTION
**Pull request by nimishamukherjee**
fix(side panel): Wrap long iteration titles.

### CODE REVIEW

**Comment by nimishamukherjee** [comment]
@SMahil , @vikram-raj do you have any suggestions for the tool tip for long iteration titles?
The tool tip displays for short titles but not for long titles.

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1607.int.rdu2c.fabric8.io

**Comment by vikram-raj** [comment]
@nimishamukherjee Need add truncate in the beginning of resolved parent path of iteration.

**Comment by vikram-raj** [comment]
@nimishamukherjee Add truncate class, width: 100% and display: inline-block to strong tag.

**Comment by SMahil** [comment]
@nimisha truncate class is already there. Its breaking because of flex and getting horizontal scrollbar. As we are removing flex and completely following patternfly classes, that will fix this issue.

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1607.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1607.int.rdu2c.fabric8.io

**Pull request merged**
