### PR TITLE
HTTP/Core Comm Error Notifications

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
With this PR, errors when communicating with the core are now signalled to the user using the notification system.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1684-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1684-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
errormessage

**Comment by vikram-raj** [comment]
@nimishamukherjee @michaelkleinhenz We need to remove all the error message text from the iteration modal and add show it by the notification system.

**Comment by mindreeper2420** [comment]
@michaelkleinhenz @nimishamukherjee @vikram-raj the iteration modal should still have errors in the form - we should not stray away from that. This design (http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/) uses both the validation errors and field error messages.

**Comment by michaelkleinhenz** [comment]
@nimishamukherjee the notification is coming up because there was a http error. So that the notification is coming up is fine, we need to look why there is a http error in that case.

**Comment by michaelkleinhenz** [comment]
And that error seems to have no reason attached (hence the "undefined"). But I'll add something that prevents undefined values to be displayed.

**Comment by michaelkleinhenz** [comment]
Ok, done, if the httpError is empty, there is no more an "undefined". Still, we need to look why there is an http error on that action. But this is unrelated to this PR.

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1684-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
