### PR TITLE
Tests for Start coding button

### PR DESCRIPTION
**Pull request by naina-verma**
- Verify start coding is visible when code base is present 
- Verify start coding is disable when creating new item
- Try clicking on start coding it should redirect

### CODE REVIEW

**Comment by sanbornsen** [comment]
[test]

**Comment by joshuawilson** [comment]
Why was this approved? The Use of TS 2.1 has caused me no end of grief in the integration. It has breaking changes from 2.0.

**Comment by sanbornsen** [comment]
I approved it because, because of the caret it was installing 2.2.x and
that was causing some failure in unit tests. We removed the caret and tried
running it with the latest version working. What is exactly failing for
you? Which version do we stick that to?

**Comment by joshuawilson** [comment]
I've been setting everything to 2.0.10. That is latest in the 2.0 series of releases. Once I get all the builds stable I will go through and upgrade to the latest TS version and latest NG version.

**Comment by sanbornsen** [comment]
Cool. I didn't know that. I'll raise a PR and fix it.
On Thu, 23 Feb 2017, 7:31 p.m. Joshua Wilson, <notifications@github.com>
wrote:

I've been setting everything to 2.0.10. That is latest in the 2.0 series of
releases. Once I get all the builds stable I will go through and upgrade to
the latest TS version and latest NG version.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/fabric8io/fabric8-planner/pull/1003#issuecomment-281998598>,
or mute the thread

**Comment by joshuawilson** [comment]
thanks

**Pull request merged**
