### PR TITLE
fix(ui): add WIT name to detail view

### PR DESCRIPTION
**Pull request by kwk**
This addresses Todd's comment.

### CODE REVIEW

**Comment by mindreeper2420** [comment]
@kwk @fabric8-ux is currently working on Detail Panel wireframe updates - should we wait for those?

**Comment by kwk** [comment]
> @kwk @fabric8io/uxd is currently working on Detail Panel wireframe updates - should we wait for those?

Let's see how the snapshot looks like once the `continuous-integration/jenkins/pr-merge` job is done. The wireframes are pretty outdated btw.

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1954-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1954-fabric8-planner.int.rdu2c.fabric8.io

**Comment by kwk** [comment]
@mindreeper2420  The list view doesn't look very good, but I like the detail view: 

screenshot from 2017-06-01 17-45-43

**Comment by mindreeper2420** [comment]
@kwk checking the snapshot, the extra info you added to the list view causes it to wrap. I'd recommend waiting for that until we've taken a little bit to think about how to update the List View, as that will also affect the Cards on the Board View.

**Comment by mindreeper2420** [comment]
@kwk I don't mind the Detail Panel change :-) I'd say keep that, but leave the List View as it currently is without icon title.

**Comment by kwk** [comment]
> @kwk I don't mind the Detail Panel change :-) I'd say keep that, but leave the List View as it currently is without icon title.

Addressed that in 	d6c9114

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1954-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@kwk snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1954-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
