### PR TITLE
Search WI within selected space (while linking the item).

### LINKED ISSUE #1604: Make searching WorkItem space aware while linking on detail dialog.
Backend task is https://github.com/almighty/almighty-core/issues/1169

### PR DESCRIPTION
**Pull request by pranavgore09**
fixes #1604 

Earlier we used to search across spaces but now selected space will be considered for searching.

New URL will look like - `http://localhost:8080/api/search?spaceID=52e7929d-879c-4936-974f-0cd7cc0aa5cc&q=log%20type:86af5178-9b41-469b-9096-57e5155c3f31` 
note the `spaceID` in the query params.

Backend still support searching across all spaces. Do not pass `spaceID` to search across all spaces.
Backend related [task](https://github.com/almighty/almighty-core/pull/1184) is already merged in master.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@pranavgore09 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1635-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1635-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
@pranavgore09 can you check the snapshot url? The work item list do not show up for me.

**Comment by fabric8cd** [comment]
@pranavgore09 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1635-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
