### PR TITLE
Remove "delete" option from WI kebab menu: Board & list view.

### PR DESCRIPTION
**Pull request by pranavgore09**
Only UI items are removed because we will need delete related logic in future for new flow.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@pranavgore09 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1754-fabric8-planner.int.rdu2c.fabric8.io

**Comment by pranavgore09** [comment]
Looks like I need to remove/comment out related tests too. !

**Comment by fabric8cd** [comment]
@pranavgore09 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1754-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1754-fabric8-planner.int.rdu2c.fabric8.io

**Comment by vikram-raj** [comment]
[test]

**Comment by fabric8cd** [comment]
@pranavgore09 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1754-fabric8-planner.int.rdu2c.fabric8.io

**Comment by vikram-raj** [comment]
[test]

**Comment by naina-verma** [comment]
@pranavgore09 , working on it

**Comment by naina-verma** [comment]
@pranavgore09 plz check https://github.com/pranavgore09/fabric8-planner/pull/1

**Comment by fabric8cd** [comment]
@pranavgore09 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1754-fabric8-planner.int.rdu2c.fabric8.io

**Comment by pranavgore09** [comment]
@naina-verma thank you for help.

@nimishamukherjee it's green now :)

**Pull request merged**
