### PR TITLE
fix(detail page): Show More/Less will be made visible based on the content height.

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Show More/Less will be made visible based on the content height.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1743-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
@mindreeper2420 fixed - https://github.com/fabric8io/fabric8-planner/pull/1743/commits/1056eefb4389943a3e2d2c463eef1f1d3a17ccbd

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1743-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1743-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1743-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
[test]

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1743-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1743-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1743-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
