### PR TITLE
fix(board): block unauthorized user to drag and drop in board view

### PR DESCRIPTION
**Pull request by vikram-raj**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1336.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1336.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1336.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1336-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1336-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
Closing this issue.
The logout listener issue applies to planner overall - #1711

**Pull request closed without merging**
