### PR TITLE
Deb's pr with all comment update

### PR DESCRIPTION
**Pull request by sanbornsen**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1822-fabric8-planner.int.rdu2c.fabric8.io

**Comment by michaelkleinhenz** [comment]
I still have the issue that when I want to delete a comment, the confirmation modal locks the screen. It looks like the darken overlay is on top of everything, locking everything up. It also darkens the modal itself. In addition, the modal is oddly positioned on the top right.

**Comment by michaelkleinhenz** [comment]
Ok, I see, that modal fix is not part of this PR. Never mind then. But please be a bit more verbose on description, expecially when doing single PRs on multiple issues. Listing the fixed problems or implemented features helps reviewing that stuff :-)

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1822-fabric8-planner.int.rdu2c.fabric8.io

**Pull request closed without merging**
