### PR TITLE
fix(dead-code): Remove TBD and POM

### PR DESCRIPTION
**Pull request by naina-verma**
Hi Team,

This PR belongs to unused code removal. 

The Unused code is related to Notification , code ,chats Dashboard Pages.Which are expected to be in the Platform (not in Plannner).
     As we are planning to move the tests outside the Planner folder (New Runtime for tests inlined).

### CODE REVIEW

**Comment by fabric8cd** [comment]
@naina-verma snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1863-fabric8-planner.int.rdu2c.fabric8.io

**Comment by naina-verma** [comment]
https://github.com/fabric8io/fabric8-planner/issues/1860

**Comment by fabric8cd** [comment]
@naina-verma snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1863-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@naina-verma snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1863-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
