### PR TITLE
Clean up of Tests (fix according to UI modifications)

### PR DESCRIPTION
**Pull request by naina-verma**
Clean up of Tests (fix according to UI modifications)
There are so many issues (Not in Mock) , but in the UI i.e

- Missing ID's in code to support tests
- Few changes in Functionality , Due to Dynamic forms (We have to make pages more scrollable)

### CODE REVIEW

**Comment by naina-verma** [comment]
[chrome #01-13] Started
[chrome #01-13] .........
[chrome #01-13]
[chrome #01-13]
[chrome #01-13] 9 specs, 0 failures
[chrome #01-13] Finished in 149.038 seconds
[chrome #01-13]

[16:56:39] I/testLogger -

[16:56:39] I/launcher - 0 instance(s) of WebDriver still running
[16:56:39] I/launcher - chrome #01-0 passed
[16:56:39] I/launcher - chrome #01-1 passed
[16:56:39] I/launcher - chrome #01-3 passed
[16:56:39] I/launcher - chrome #01-2 passed
[16:56:39] I/launcher - chrome #01-5 passed
[16:56:39] I/launcher - chrome #01-6 passed
[16:56:39] I/launcher - chrome #01-7 passed
[16:56:39] I/launcher - chrome #01-8 passed
[16:56:39] I/launcher - chrome #01-9 passed
[16:56:39] I/launcher - chrome #01-10 passed
[16:56:39] I/launcher - chrome #01-4 passed
[16:56:39] I/launcher - chrome #01-11 passed
[16:56:39] I/launcher - chrome #01-12 passed
[16:56:39] I/launcher - chrome #01-13 passed
4444/tcp:            13355
8088/tcp:            13385
Functional tests OK

**Comment by nimishamukherjee** [comment]
[test]

**Comment by rawlingsj** [comment]
@nimishamukherjee FWIW the reason the fabric8 CI fails is because of the `local_run_functional_tests.sh` merge conflict mentioned above.  Once resolved the CI should hopefully pass.

**Comment by fabric8cd** [comment]
@naina-verma snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1527-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@naina-verma snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1527-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@naina-verma snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1527-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
