### PR TITLE
Fixed mock http end points and made it available for external packages using http services

### PR DESCRIPTION
**Pull request by sanbornsen**

### CODE REVIEW

**Comment by joshuawilson** [comment]
This changes the global to default to true and never be set to false. So we are always in test mode?

btw, what was wrong with using observables?

**Comment by sanbornsen** [comment]
@joshuawilson even before the subscriber could find the mode, the services were firing up the API  and considering it a production mode it was hitting the API URL instead of mock HTTP. Try running it into in-memory mode, you'll understand the problem.

**Comment by michaelkleinhenz** [comment]
@joshuawilson mmh..I think the mode gets set by the env. The default is just the initializing. On the Observables: the mode value is not asynchronously established, why use Observables?

**Comment by joshuawilson** [comment]
if you want to asynchronously update the global state then you read initial values from a config.json or remote server and you have an observer that emits those values

**Comment by joshuawilson** [comment]
The use of rxjs is philosophical in nature. I prefer it. I think functional programming is a better style. That said, what you have done works and we need to keep moving. So I'm going to merge it. If something doesn't work in this, then we fix it.

**Pull request merged**
