### PR TITLE
fix(docs): update the README to have the commit syntax needed to release

### PR DESCRIPTION
**Pull request by joshuawilson**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@joshuawilson snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2045-fabric8-planner.int.rdu2c.fabric8.io

**Comment by debloper** [comment]
The information added in this patch is already part of the contributing doc, as mentioned at the end of readme file. This one might have to be backed/reverted.

**Comment by Preeticp** [comment]
Reverted through #2051

**Comment by joshuawilson** [comment]
It is fine to revert it. I needed it kick off the build since the previous builds didn't follow the syntax. So I thought it appropriate to add it. I'm thinking that not enough people are looking at the other doc.

**Pull request merged**
