### PR TITLE
WIP - refactor(project): Use the new `Number` attribute to display a work item number (#1925)

### PR DESCRIPTION
**Pull request by xcoulon**
This is a WIP for 2 reasons:
- it contains a fix for #1948 (I'll rebase the patch once this PR is merged)
- it should be merged only once https://github.com/almighty/almighty-core/pull/1338 is merged on the back-end

### CODE REVIEW

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1956-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1956-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
@xcoulon please update this PR.

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1956-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1956-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@xcoulon snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1956-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
