### PR TITLE
fix(table-config): Tooltip not displaying in attributes table

### PR DESCRIPTION
**Pull request by abhinandan13jan**
<strong>Note: If there are pending changes to the PR, prefix the PR title with "WIP" and add the label "DO NOT MERGE"</strong>

### Mandatory
 - [x] What does this PR do? 
  Import tooltip in order to pop up tooltip when hovering over the icons. 
- [x] What issue/task does this PR references?
  fixes #4633
https://github.com/openshiftio/openshift.io/issues/4633
- [x] Are the tests Included?
   No additional tests required

### Optional
- [ ] Is the documentation Included?

- [ ] Are the Release Notes included?

- [ ] @mention(s) to expected reviewer(s) included

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @abhinandan13jan for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/blob/874fb469a1fe33d0ce8ec71e3d4b2f616cbd181d/.ike-prow/test-keeper.yaml).

**Comment by joshuawilson** [comment]
please add a reference to the issue, either as a 'ref' or as `fixes #theNumberOfTheIssue`

**Comment by abhinandan13jan** [comment]
@joshua Added reference

**Comment by abhinandan13jan** [comment]
@sahil143 Can you check if the PR looks ok? Without the tooltip in place I am not able to work on fixing this issue https://github.com/openshiftio/openshift.io/issues/3856

**Review by sahil143 — APPROVED** [review]

**Comment by joshuawilson** [comment]
[test]

**Comment by abhinandan13jan** [comment]
@joshuawilson No testcases as only metadata of the code has changed

**Pull request merged**
