### PR TITLE
fix(pipeline): improve PR job stability by disabling concurrent builds

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rawlingsj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1889-fabric8-planner.int.rdu2c.fabric8.io

**Comment by rawlingsj** [comment]
@michaelkleinhenz it seems the fabric8 CI pipeline is failing, I wonder if another commit has been merged which causes this 
```
/home/jenkins/workspace/uto_fabric8-planner_PR-1889-QGAACZHZYJSXYCLKSXO4KDSD3QRQZTV3WY3TQWBMFD633ETAA2KQ@2/fabric8-ui/src/fabric8-planner/src/app/work-item/work-item.service.json doesn't exist
```
As the first time the CI job ran on this PR it worked but now we get these errors ^^

**Comment by rawlingsj** [comment]
@michaelkleinhenz it seems this is happening on all planner fabric8 CI PR jobs and they're backing up the infra.  I'll try and put a timeout on these commit but I really think the issue needs to be looked at sooner rather than later.

**Comment by rawlingsj** [comment]
@michaelkleinhenz I've added a pipeline timeout which should hopefully avoid the planner blocking other jobs on the CD infra.  I'd like to get this merged.

**Comment by nimishamukherjee** [comment]
[test]

**Pull request merged**
