### PR TITLE
fix(board): update iteration count on WI state change

### PR DESCRIPTION
**Pull request by vikram-raj**
Fix: fabric8io/fabric8-ui#1209

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1846-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1846-fabric8-planner.int.rdu2c.fabric8.io

**Comment by vikram-raj** [comment]
[test]

**Comment by vikram-raj** [comment]
@nimishamukherjee You mean number get updated but the progress bar does not.

**Comment by nimishamukherjee** [comment]
statusbar

I think the status bas problem should be a separate story as the status bar does not get updated on the list view also.

Also on the board, how is the status count calculated?
It it selected sprint and selected work item type?
Or
Selected sprint and all work item type?

Here is my use case:
I have two work item types - a feature and a bug
I set their status to close in the list view
Navigate to board view - the progress shows 2 of 2 completed and the bar is blue
Select bug as the work item type, and drag the work item from close to in progress
The progress shows 0 of 0 completed and the bar is still blue.

The status number

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1846-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1846-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
