### PR TITLE
test(automation): browser logs separated

### PR DESCRIPTION
**Pull request by rgarg1**
Browser logs, that indicate success or failure of test were limited only to the console. Now they get logged to a new log file named browser_logs.log for effective debugging and test status tracking.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1946-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1946-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1946-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1946-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1946-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1946-fabric8-planner.int.rdu2c.fabric8.io

**Comment by rgarg1** [comment]
Kindly merge

**Comment by fabric8cd** [comment]
@rgarg1 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1946-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
@rgarg1 the merge option will get enabled after the CentOs build is green.

**Comment by nimishamukherjee** [comment]
[test]

**Pull request merged**
