### PR TITLE
fix(itr-association):fix css for long wi title in iteration association

### PR DESCRIPTION
**Pull request by SMahil**
fix css for long wi title in iteration association modal
screen shot 2017-04-26 at 2 39 56 pm

Closes: #1749

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1777-fabric8-planner.int.rdu2c.fabric8.io

**Comment by mindreeper2420** [comment]
@SMahil this might also bring up the need to investigate Titles only having random characters with no spaces. The cases of 30+ characters with no spaces is rare :-)

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1777-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1777-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
