### PR TITLE
Add toast notification on start iteration.

### PR DESCRIPTION
**Pull request by vikram-raj**
#871

### CODE REVIEW

**Comment by nimishamukherjee** [comment]
How long does the toast notification stay is the user does not dismiss it?

**Comment by nimishamukherjee** [comment]
[test]

**Comment by Essjaysee** [comment]
@nimishamukherjee Our understanding in UXD was that toast notifications were below the cut line (and not going to be in for the current scope).   Did that change?  Details about interactions for toast notifications, like how long to show it, can be found here: http://www.patternfly.org/pattern-library/communication/toast-notifications/#/api for details about the interactions.  Thanks!

**Comment by catrobson** [comment]
We also should building these as a common component in the Platform, not just into the planner.

**Pull request merged**
