### PR TITLE
fix(comments): Add visual differentiation for the comments expanded/collapsed state. Fixes #1603.

### LINKED ISSUE #1603: Comments Row does not change between active/inactive identifiers
The row for opening and closing the Comments area should have a visual differentiations when it is opened versus closed. Currently, it is highlighted (and underlined) with the PatternFly blue state.

In order to keep uniformity, it should match the visual identifiers that the 'Total Links' row has, where it changes to the PatternFly grey when it has been collapsed.

screen shot 2017-04-12 at 7 15 22 am

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Add visual differentiation for the comments expanded/collapsed state. Fixes #1603.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1641-fabric8-planner.int.rdu2c.fabric8.io

**Comment by SMahil** [comment]
@nimishamukherjee @mindreeper2420 Changes are fine but I have one question around this. If Total Links section is not collapsed would the comments section also collapsed or not? Right not both the sections can be uncollapsed at same time

**Comment by mindreeper2420** [comment]
@smahil the current configuration is fine - both sections can be open at the same time. We don't want sections auto-collapsing at the moment.

**Comment by fabric8cd** [comment]
@nimishamukherjee snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1641-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
