### PR TITLE
fix(board): fix alignment of type selector

### PR DESCRIPTION
**Pull request by mindreeper2420**
fix the alignment of the type selector dropdown to justify to the right of the button

### CODE REVIEW

**Comment by mindreeper2420** [comment]
@nimishamukherjee this fixes the alignment error as noted by @vikram-raj in PR https://github.com/fabric8io/fabric8-planner/pull/1660

**Comment by mindreeper2420** [comment]
screen shot 2017-04-19 at 6 40 31 am

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1672-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1672-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
