### PR TITLE
fix(detailtypepanel): fix add type selector panel to cover full screen

### PR DESCRIPTION
**Pull request by SMahil**
fix add type selector panel to cover full screen

Closes : #1313

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1564.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1564.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
@rawlingsj this snapshot is incorrect

> @SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1564.int.rdu2c.fabric8.io

**Comment by rawlingsj** [comment]
@nimishamukherjee dam!  ok can you give me a bit more detail of what's wrong?

**Comment by nimishamukherjee** [comment]
https://fabric8-ui-fabric8-ui-pr-1564.int.rdu2c.fabric8.io/nmukherj/SummerFun/plan (select a space > plan, click on the + icon to add a work item)
prdeployed
This was how the UI was yesterday.

After the fixes were done, locally when I run this PR the screen looks like:
fixedpr

@rawlingsj - the snapshot generated for each commit/push, after the initial PR creation, do not seem to have the latest changes.

**Comment by fabric8cd** [comment]
@SMahil snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1564.int.rdu2c.fabric8.io

**Pull request merged**
