### PR TITLE
Tree only displays no-parent items now; with toggle between that and flat mode

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
The tree now displays a "proper" tree without obvious dupes. Also added a toggle that enables switching between the tree and a flat list. 

KNOWN ISSUE: if the tree is expanded when switching the mode, the user will experience some weird issues. Problem is there seems to be no way of force-collapsing the tree yet. We will fix that in a later PR.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1742-fabric8-planner.int.rdu2c.fabric8.io

**Comment by mindreeper2420** [comment]
@michaelkleinhenz a few things:
- When in 'Flat' view mode, it should just display them all at the same indentation level
- When I switch back and forth between "hierarchy" and "flat", a 'Loading...' message is persistent
- The expand/collapse caret is hard to recognize next to the Status icon

screen shot 2017-04-24 at 10 34 24 am

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1742-fabric8-planner.int.rdu2c.fabric8.io

**Comment by michaelkleinhenz** [comment]
@mindreeper2420 on the "Loading" issue: yes, that is a known issue that we can not fix right now. The upstream tree is broken and does not have an API call to collapse everything before switching. We have to live with that for now.
On the slight indent and the caret position: these are issues that were there before. Let's fix them in a seperate PR as this one is more critical to have it in prod.

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1742-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
