### PR TITLE
fix(http): Centralized headers to HTTP abstract

### PR DESCRIPTION
**Pull request by sanbornsen**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1970-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1970-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1970-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1970-fabric8-planner.int.rdu2c.fabric8.io

**Comment by sanbornsen** [comment]
[test]

**Pull request merged**
