### PR TITLE
fix(table-config): Set arrows as disabled when no column is selected

### PR DESCRIPTION
**Pull request by abhinandan13jan**
### Mandatory
 - [x] What does this PR do? 
     Sets arrows in attribute settings as disabled when no attribute is selected in table-config component. 
- [x] What issue/task does this PR references?
     This PR addresses the following settings issue 
      https://github.com/openshiftio/openshift.io/issues/3856
- [x] Are the tests Included?
      Yes, testcases have been included.
___
Please note: This PR will work properly after the tooltip is in place ( https://github.com/fabric8-ui/fabric8-planner/pull/2818 ).

### CODE REVIEW

**Review by sahil143 — CHANGES_REQUESTED** [review]
@abhinandan13jan I'm not seeing any tooltip regardless of an attribute is selected or not and arrow button should be disabled(greyed out) when the attribute is not selected, I see you have only added the tooltip.

**Comment by abhinandan13jan** [comment]
@sahil143 This PR is dependant on the other PR on tooltip ( https://github.com/fabric8-ui/fabric8-planner/pull/2818 ), which must be merged first. I see that the other PR is now merged. Can you check it again. The arrows are of type 'span' and 'span' doesn't have a disabled property so I've changed on the tooltip message part saying "Please select an attribute". Should I grey-out the spans as well using CSS?

**Comment by sahil143** [comment]
Yes, You can disable using the css

**Comment by abhinandan13jan** [comment]
@sahil143 Added CSS

**Comment by nimishamukherjee** [comment]
@abhinandan13jan the behaviour works only for the first time. If I move the attributes back and forth, the arrows do not grey out.
nexttime

**Review by joshuawilson — CHANGES_REQUESTED** [review]
This doesn't build. Please make these changes in fabric8-ui now and close this PR when done.

**Comment by abhinandan13jan** [comment]
@joshuawilson ok

**Pull request closed without merging**
