### PR TITLE
fix(iteration): disappear of iteration title when create child iterat…

### PR DESCRIPTION
**Pull request by vikram-raj**
…ion modal open

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1591.int.rdu2c.fabric8.io

**Comment by vikram-raj** [comment]
@nimishamukherjee It is failing in firefox, work fine in chrome. I am fixing it.

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1591.int.rdu2c.fabric8.io

**Comment by rawlingsj** [comment]
@nimishamukherjee ok many thanks - I'll have a look at what's going on.  Sounds like something to do with applying the updated snapshot version.

**Comment by fabric8cd** [comment]
@vikram-raj snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1591.int.rdu2c.fabric8.io

**Pull request merged**
