### PR TITLE
bug: make header navigation responsive in mobile view

### PR DESCRIPTION
**Pull request by SMahil**
make header navigation responsive in mobile view

#592

### CODE REVIEW

**Comment by nimishamukherjee** [comment]
@SMahil the functional tests are failing.

**Comment by SMahil** [comment]
@naina-verma Please have a look to the func tests. Now we have hidden header in mobile view and thats why tests are failing

**Comment by naina-verma** [comment]
@SMahil , Hey i have gone through your branch , it looks like UI has been changed for mobile view , so needed little modification in the functional tests.
Please wait for some time , i will send a PR to your branch soon :)

**Comment by joshuawilson** [comment]
@SMahil While it is nice to have this responsive, we are not going to use this Header or menu at all. The Header is maintained in fabric-ui.

**Comment by SMahil** [comment]
@joshuawilson yes we are not working on this now

**Comment by joshuawilson** [comment]
@SMahil can we either close this or update it and get it merged?

**Comment by SMahil** [comment]
@joshuawilson I think we should get it merged because the issue persists if we move the header to platform. 
@naina-verma worked on its functional tests. Once it got resolved we are good to merge it

**Comment by nimishamukherjee** [comment]
@SMahil are we merging this PR? If yes, please rebase.

**Comment by SMahil** [comment]
@nimishamukherjee tests are failing. Naina has raised the PR but it has conflicts. Once tests are fine  We are good to merge it

**Comment by nimishamukherjee** [comment]
Closing this PR as planner will not have a header and the platform header is completely different from what we have.

**Pull request closed without merging**
