### PR TITLE
fix(treelist): Refactored treelist to better mimic dnd mock-ups

### PR DESCRIPTION
**Pull request by dlabrecq**
Note that this depends on this ngx-widgets PR:
https://github.com/fabric8-ui/ngx-widgets/pull/51

### CODE REVIEW

**Comment by dlabrecq** [comment]
FYI @vikram-raj, made some final style tweaks after testing ngx-widgets in the planner ui.

**Comment by michaelkleinhenz** [comment]
Should we wait to merge this until fabric8-ui/ngx-widgets#51 is merged? @dlabrecq

**Comment by dlabrecq** [comment]
Yes. We need to merge ngx-widgets, first. @joshuawilson ?

**Comment by michaelkleinhenz** [comment]
Interesting is that the check has succeeded here. It should not. We had that on another PR from @vikram-raj  too and merged it, so current master requires the new ngx-widgets version and are broken right now.
@ldimaggi can you take a look why the tests here did not fail?

**Comment by michaelkleinhenz** [comment]
[test]

**Comment by dlabrecq** [comment]
FYI, the planner UI only requires the latest ngx-widgets so it can achieve the desired layout shown in the mock-ups. I refactored tree-list to add some new attributes to achieve this. However, it won't generate an error if they are not used.

I don't expect the tests would fail. Instead, the tree list simply won't visually appear the way we expect it to in the planner UI. For example, you may see extra white space between rows and drag and drop may not function properly.

**Comment by dlabrecq** [comment]
Rebased

**Comment by dlabrecq** [comment]
@michaelkleinhenz Can this be merged? fabric8-ui/ngx-widgets#51 has been merged and I've rebased.

**Pull request merged**
