### PR TITLE
fix(comments): fix vanishing comments on WI save.

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
Fixes the vanishing comments when a WI is saved on the detail view (ex, when the state is changed).

### CODE REVIEW

**Comment by michaelkleinhenz** [comment]
[test]

**Comment by joshuawilson** [comment]
[test]

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz please resolve conflicts.

**Comment by fabric8cd** [comment]
@michaelkleinhenz snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1832-fabric8-planner.int.rdu2c.fabric8.io

**Pull request merged**
