### PR TITLE
fix(header): Added If-None-Match header to ignore all the cache

### PR DESCRIPTION
**Pull request by sanbornsen**
This needs to be merged first - https://github.com/almighty/almighty-core/pull/1260

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sanbornsen snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1791-fabric8-planner.int.rdu2c.fabric8.io

**Comment by joshuawilson** [comment]
Revert this as it is only a temp fix, the real solution is in https://github.com/almighty/almighty-core/pull/1270

**Comment by joshuawilson** [comment]
We are going to try it with this still in place. Please check with @aslakknutsen before you revert this.

**Comment by alexeykazakov** [comment]
https://github.com/almighty/almighty-core/pull/1270 is prod-preview now. We can revert this one in prod-preview too now.

**Pull request merged**
